---
config:
  theme: default
---

classDiagram

    class Mission {
        -missionId: String
        -date: Date
        -location: String
        -outcome: String
        -damageCost: long
        -curse: Curse
        -comment: String
        -sorcerers: List~Sorcerer~
        -techniques: List~Technique~
    }

    class Curse {
        -name: String
        -threatLevel: String
    }

    class Sorcerer {
        -name: String
        -rank: String
    }

    class Technique {
        -name: String
        -type: String
        -owner: Sorcerer
        -ownerName: String
        -damage: int
    }


    Mission o-- Curse : Содержит
    Mission o-- Sorcerer : Задействует
    Mission o-- Technique : Использует
    Technique *-- Sorcerer : Владеет
