
package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import logic.Engine; // Ваш движок
import models.Mission;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

public class MainFrame {
    private JTable missionsTable;
    private JPanel Main;
    private JButton importButton;

    private final Engine engine;
    private final MissionTableModel tableModel;

    public MainFrame() {
        this.engine = new Engine();
        this.tableModel = new MissionTableModel(engine.getAllMissions());

        missionsTable.setModel(tableModel);

        missionsTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(e)) {
                    int row = missionsTable.getSelectedRow();
                    if (row != -1) {
                        int modelRow = missionsTable.convertRowIndexToModel(row);

                        String missionId = (String) tableModel.getValueAt(modelRow, 0);

                        engine.findMissionById(missionId).ifPresent(mission -> {
                            showMissionDetails(mission);
                        });
                    }
                }
            }
        });

        importButton.addActionListener(e -> {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new FileNameExtensionFilter(
                "Mission files (JSON, XML, TXT)", "json", "xml", "txt"));

            int returnValue = fileChooser.showOpenDialog(Main);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = fileChooser.getSelectedFile();
                try {
                    engine.importMission(selectedFile);

                    tableModel.fireTableDataChanged();

                    JOptionPane.showMessageDialog(Main, "Миссия успешно добавлена!");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(Main,
                        "Ошибка при импорте: " + ex.getMessage(),
                        "Ошибка", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    private void showMissionDetails(Mission mission) {
        JFrame detailFrame = new JFrame("Детали миссии: " + mission.getMissionId());
        detailFrame.setContentPane(new MissionFrame(mission).getMainPanel());
        detailFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        detailFrame.pack();
        detailFrame.setLocationRelativeTo(Main);
        detailFrame.setVisible(true);
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Управление магическими миссиями");
        frame.setContentPane(new MainFrame().Main);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Main = new JPanel();
        Main.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        Main.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        importButton = new JButton();
        importButton.setLabel("Импорт");
        importButton.setText("Импорт");
        panel1.add(importButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        Main.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        missionsTable = new JTable();
        scrollPane1.setViewportView(missionsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Main;
    }

}

